# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'trashGrav-SEPM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for trashGrav-SEPM
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  
end
